id = "mcp-server-figma"
name = "Framelink Figma MCP Server"
description = "Model Context Protocol Server for Figma"
version = "0.0.3"
schema_version = 1
authors = ["Jeffrey Guenther <guenther.jeffrey@gmail.com>"]
repository = "https://github.com/LoamStudios/zed-mcp-server-figma"

[context_servers.mcp-server-figma]
name = "Framelink Figma MCP Server"
